In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
b = np.array(range(0, 10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
c = np.array(range(0, 10, 2))
c

array([0, 2, 4, 6, 8])

In [4]:
print('c.shape = {}'.format(c.shape))
print('c.ndim = {}'.format(c.ndim))
print('c.dtype = {}'.format(c.dtype))
print('c.size = {}'.format(c.size))
print('c.itemsize = {}'.format(c.itemsize))

c.shape = (5,)
c.ndim = 1
c.dtype = int32
c.size = 5
c.itemsize = 4


In [5]:
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print('a = {}'.format(a))
print('최댓값 : {}'.format(a.max())) 
print('최솟값 : {}'.format(a.min())) 
print('평균 : {}'.format(a.mean())) 

a = [23 45 67  7  2 30 34 82]
최댓값 : 82
최솟값 : 2
평균 : 36.25


In [6]:
b = np.random.randint(0, 100, size=10)
print('b = {}'.format(b))
print('최댓값 : {}'.format(b.max())) 
print('최솟값 : {}'.format(b.min())) 
print('평균 : {}'.format(b.mean())) 

b = [55  1 96 90 26 34  3 23 22 43]
최댓값 : 96
최솟값 : 1
평균 : 39.3


In [7]:
c = np.append(a, b)
print('c = {}'.format(c))

c = [23 45 67  7  2 30 34 82 55  1 96 90 26 34  3 23 22 43]


In [8]:
a = np.arange(1, 10, 1).reshape(3,3)
print('a = {}'.format(a))

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
b = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
print('b = {}'.format(b))

b = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [10]:
np.full((3,3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [11]:
a + b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
a - b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [13]:
a * b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
a / b

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [15]:
a @ b

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [16]:
a ** b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [17]:
a1 = np.full((3,3), 2)
print('a1 =', a1)

a1 = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [18]:
a2 = np.arange(1, 13)
print('a2 = ', a2)

a2 =  [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
a3 = np.arange(3, 50, 3)
print('a3 = ', a3)

a3 =  [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [20]:
a4 = np.linspace(0, 20, 5)
print('a4 =', a4)

a4 = [ 0.  5. 10. 15. 20.]


In [21]:
a1 = np.arange(1, 13).reshape(2, 6)
print('a1 =', a1)

a1 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
a2 = np.arange(1, 31).reshape(3, 10)
print('a2 =', a2)

a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [23]:
a3 = a2.reshape(6, 5)
print('a3 =', a3)

a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [24]:
a4 = np.transpose(a3)
print('a4 =', a4)

a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [26]:

a = np.random.randint(0, 100, size=15).reshape(3, 5)
print('a =', a)
print('a의 열방향 최댓값 :', a.max(axis=0))
print('a의 열방향 최솟값 :', a.min(axis=0))
print('a의 열방향 평균 :', a.mean(axis=0))

a = [[97 15 55 58 89]
 [73 60 42 28 12]
 [36 81 71 37 41]]
a의 열방향 최댓값 : [97 81 71 58 89]
a의 열방향 최솟값 : [36 15 42 28 12]
a의 열방향 평균 : [68.66666667 52.         56.         41.         47.33333333]


In [27]:
print('a의 행방향 최댓값 :', a.max(axis=1))
print('a의 행방향 최솟값 :', a.min(axis=1))
print('a의 행방향 평균 :', a.mean(axis=1))

a의 행방향 최댓값 : [97 73 81]
a의 행방향 최솟값 : [15 12 36]
a의 행방향 평균 : [62.8 43.  53.2]


In [28]:
a = np.arange(1, 11)
print('a =', a)
b = a[np.array([1, 3, 5, 7])]
print('b =', b)

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]


In [29]:
b = a[5:]
print('b =', b)

b = [ 6  7  8  9 10]


In [30]:
c = a[6:]
print('c =', c)

c = [ 7  8  9 10]


In [32]:
d = a[:3]
print('d =', d)

d = [1 2 3]


In [33]:
e = a[::2]
print('e =', e)

e = [1 3 5 7 9]


In [34]:
f = a[::-2]
print('f =', f)

f = [10  8  6  4  2]


In [35]:
a = np.arange(0, 24).reshape(4, 3, 2)

print('{:13s}{:5s}'.format('index', 'element'))
for i in np.ndindex(a.shape):
    print('{}{:7d}'.format(i, a[i]))

index        element
(0, 0, 0)      0
(0, 0, 1)      1
(0, 1, 0)      2
(0, 1, 1)      3
(0, 2, 0)      4
(0, 2, 1)      5
(1, 0, 0)      6
(1, 0, 1)      7
(1, 1, 0)      8
(1, 1, 1)      9
(1, 2, 0)     10
(1, 2, 1)     11
(2, 0, 0)     12
(2, 0, 1)     13
(2, 1, 0)     14
(2, 1, 1)     15
(2, 2, 0)     16
(2, 2, 1)     17
(3, 0, 0)     18
(3, 0, 1)     19
(3, 1, 0)     20
(3, 1, 1)     21
(3, 2, 0)     22
(3, 2, 1)     23


In [36]:
np.concatenate((a[0, 0], a[1, 0]), axis=0)
np.concatenate((a[0, 0], a[2, 1]), axis=0)
np.concatenate((a[0], a[1]), axis=0)
np.concatenate((a[0], a[1]), axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [38]:
a = np.arange(0, 16).reshape(4, 4)
print('행렬 a :')
print(a)
b = a[:, 1]
print('b =', b)
c = a[2, 1:]
print('c =', c)
d = a[:2, :2]
print('d =', d)
e = a[1:3, 1:3]
print('e =', e)

행렬 a :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]


In [39]:
f = a[0:2, 0:3].flatten()
print('f =', f)
g = a[2:, :].flatten()
print('g =', g)
h = np.concatenate((a[1, 1:4], a[3, 1:4])).flatten()
print('h =', h)

f = [0 1 2 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


In [40]:
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]], dtype='int32')
B = np.array([0, 9, 8], dtype='int32')
x = np.linalg.solve(A, B)
print('x = {:4.1f}, y = {:4.1f}, z = {:4.1f}'.format(x[0], x[1], x[2]))

x =  1.0, y =  2.0, z =  3.0


In [41]:
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]], dtype='int32')
det = np.linalg.det(A)
print('det(A) = {:4.1f}'.format(det))

det(A) = -11.0


In [42]:
a1 = np.array([[-1, 3], [2, 1]])
a2 = np.array([[2, 3], [1, 1]])
a3 = np.array([[2, -1], [1, 2]])
det = 1 * np.linalg.det(a1) - 1 * np.linalg.det(a2) - 1 * np.linalg.det(a3)
print('det(A) = {:4.1f}'.format(det))

det(A) = -11.0


In [43]:
a = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
print('a =', a)

a = [0 0 0 0 0 0 0 0 0 0]


In [44]:
n_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int32')
print(n_arr.itemsize)
print(n_arr.shape)

4
(10,)


In [45]:
n_arr = np.array([1,2,3,4,5 6,7,8,9,10], dtype='int64')
print('n_arr의 크기 :{} bytes'.format(n_arr.itemsize * n_arr.size))

SyntaxError: invalid syntax (639732358.py, line 1)

In [47]:
n_arr = np.array([1.5,2.2,3.2,4.9], dtype='float64')
print('n_arr의 크기:{} bytes'.format(n_arr.itemsize * n_arr.size))

n_arr의 크기:32 bytes


In [48]:
a = np.arange(1, 11)
print('a =', a)
a = a[::-1]
print('a =', a)
a = a.reshape(2,5)
print(a)
a = a.reshape(5, 2)
print(a)

a = [ 1  2  3  4  5  6  7  8  9 10]
a = [10  9  8  7  6  5  4  3  2  1]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


In [49]:
print(np.arange(1, 17).reshape(4,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
